import pandas as pd
bm = pd.read_csv("data/interim/beatmaps.csv")
mh = pd.read_csv("data/interim/mania_high.csv")
print(bm.head(3).to_string()[:600])
print()
print("beatmap 20305 in beatmaps.csv:")
print(bm[bm.beatmap_id == 20305].to_string())
sub = bm[bm.beatmap_id.isin(mh.beatmap_id.unique())]
print("\nbeatmaps referenced by mania_high:", mh.beatmap_id.nunique(), "present:", len(sub))
print("their playmode counts:", sub.playmode.value_counts().to_dict())
print("their keys counts:", sub["keys"].value_counts().head(8).to_dict())
print("\nmania_high users:", mh.user_id.nunique())
print("plays per user describe:")
print(mh.groupby("user_id").size().describe())
pair = mh.groupby(["user_id","beatmap_id"]).size()
print("\nplays per (user,beatmap) pair value counts (top):")
print(pair.value_counts().sort_index().head(10).to_string())
print("pairs:", len(pair), "rows:", int(pair.sum()), "pairs>=2:", int((pair>=2).sum()), "pairs>=3:", int((pair>=3).sum()))
print("max plays per pair:", int(pair.max()))
